version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=htpps://<yourdomain.here.com> # DO NOT ALTER 'HTTPS://'
      - DB_HOST=bookstack_db
      - DB_USER=<youruser>
      - DB_PASS=<yourpassword>
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<ROOTPASSWORD>
      - TZ=Country/City
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=<youruser>
      - MYSQL_PASSWORD=<yourpassword>
    volumes:
      - ./bookstack/config:/config
    restart: unless-stopped
